import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teraret Managed Cloud Private Limited | AWS, Google Cloud, Digital Ocean</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Teraret (Tera Byte Retention )
        </h1>

        <p className={styles.description}>
        Our Managed cloud  solution allows each customer to choose which IT functions they wish to manage in-house, while leaving all the rest to our cloud engineers. 
       
        Our Managed cloud services can include infrastructure and application level support.
       
        Our engineers manage not only the customers’ computing, storage, networks, and operating systems, but also the complex tools and application stacks that run on top of that infrastructure.
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Cloud</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Application</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Database</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>DevOps</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://teraret.com"
          
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/teraret.svg" alt="Teraret Logo" width={80} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
